#   Version 10.4.2604.12

##############################################################
# default values for fields                                  #
##############################################################
